apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: order-processor
  name: order-processor-deployment
  namespace: order-processor

spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-processor

  template:
    metadata:
      labels:
        app: order-processor
    spec:
      containers:
        - name: order-processor
          image: matejalex/orderprocessor:latest
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  key: PORT
                  name: order-processor-configmap

