apiVersion: v1
kind: Service
metadata:
  name: order-processor-service
  namespace: order-processor
spec:
  selector:
    app: order-processor
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081