apiVersion: v1
kind: ConfigMap

metadata:
  labels:
    app.kubernetes.io/instance: eg
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: gateway-helm
    app.kubernetes.io/version: latest
    helm.sh/chart: gateway-helm-v0.0.0-latest
  name: envoy-gateway-config
  namespace: envoy-gateway-system
data:
  envoy-gateway.yaml: |-
    apiVersion: gateway.networking.k8s.io/v1
    Kind: EnvoyGateway
    logging:
      level:
        default: debug