apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: order-processor-route
  namespace: order-processor
spec:
  parentRefs:
    - name: gateway
      sectionName: http
  hostnames:
    - "order.processor"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: order-processor-service
          port: 80



